# fly.toml app configuration file generated for discord-bot-next on 2023-06-03T09:32:05-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "discord-bot-next"
primary_region = "atl"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = false
  auto_start_machines = false
  min_machines_running = 1
